openapi: 3.0.3
info:
  title: Petstore API
  description: A simple example API for demonstrating OpenAPI tool generation
  version: 1.0.0
servers:
  - url: https://petstore3.swagger.io/api/v3
    description: Main production server
paths:
  /pets:
    get:
      operationId: listPets
      summary: List all pets
      description: Returns a list of pets from the store
      parameters:
        - name: limit
          in: query
          description: Maximum number of pets to return
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
            default: 20
        - name: category
          in: query
          description: Filter pets by category
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        '400':
          description: Invalid request
        '500':
          description: Internal server error
    post:
      operationId: createPet
      summary: Create a new pet
      description: Adds a new pet to the store
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPet'
      responses:
        '201':
          description: Pet created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '400':
          description: Invalid input
        '500':
          description: Internal server error
  /pets/{petId}:
    get:
      operationId: getPet
      summary: Get a pet by ID
      description: Returns a single pet by its ID
      parameters:
        - name: petId
          in: path
          description: ID of the pet to retrieve
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Pet details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
        '500':
          description: Internal server error
    put:
      operationId: updatePet
      summary: Update a pet
      description: Updates an existing pet in the store
      parameters:
        - name: petId
          in: path
          description: ID of the pet to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPet'
      responses:
        '200':
          description: Pet updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
        '400':
          description: Invalid input
        '500':
          description: Internal server error
    delete:
      operationId: deletePet
      summary: Delete a pet
      description: Removes a pet from the store
      parameters:
        - name: petId
          in: path
          description: ID of the pet to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Pet deleted successfully
        '404':
          description: Pet not found
        '500':
          description: Internal server error

components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the pet
        name:
          type: string
          description: Pet's name
        category:
          type: string
          description: Pet's category (e.g., dog, cat, bird)
        status:
          type: string
          enum: [available, pending, sold]
          description: Pet's availability status
        tags:
          type: array
          items:
            type: string
          description: Tags associated with the pet
    NewPet:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Pet's name
        category:
          type: string
          description: Pet's category
        status:
          type: string
          enum: [available, pending, sold]
          description: Pet's availability status
          default: available
        tags:
          type: array
          items:
            type: string
          description: Tags associated with the pet