package toon
package toon

import (
	"encoding/json"











































































































































































































































}	return sb.String()		}		}			sb.WriteString(fmt.Sprintf("  [%s] %s\n", msg.Role, content))			}				content = content[:100] + "..."			if len(content) > 100 {			content := msg.Content		for _, msg := range c.Messages[start:] {		}			start = 0		if start < 0 {		start := len(c.Messages) - 3		// Show last 3 messages		sb.WriteString(fmt.Sprintf("[HISTORY] Recent messages: %d\n", len(c.Messages)))	if len(c.Messages) > 0 {		}		sb.WriteString(fmt.Sprintf("  ... and %d more tools\n", len(c.Tools)-5))	if len(c.Tools) > 5 {		}		}			sb.WriteString(fmt.Sprintf("  %d. %s - %s\n", i+1, tool.Name, tool.Description))		if i < 5 { // Show max 5 tools to save tokens	for i, tool := range c.Tools {		sb.WriteString(fmt.Sprintf("[TOOLS] Available: %d\n", len(c.Tools)))	sb.WriteString(fmt.Sprintf("[CONTEXT] Agent: %s | Session: %s\n", c.Metadata.Agent, c.Metadata.SessionID))		var sb strings.Builderfunc (c *Context) FormatForModel() string {// Includes context summary and available tools// FormatForModel returns a formatted string optimized for model consumption}	return len(json) / 4	// Rough token estimation: ~4 characters per token	}		return 0	if err != nil {	json, err := json.Marshal(c)func (c *Context) TokenCount() int {// Rough estimation: 1 token ~= 4 characters// TokenCount estimates the token count of the context}	)		len(c.Tools), len(c.Messages), len(c.State),		c.Version, c.Metadata.Agent, c.Metadata.Source,		"{\"v\":%q,\"ag\":%q,\"src\":%q,\"t\":%d,\"m\":%d,\"s\":%d}",	return fmt.Sprintf(func (c *Context) Summary() string {// Summary returns a token-efficient summary of the context}	return sb.String()		}		}			sb.WriteString(fmt.Sprintf("  - %s (%s): %s\n", tool.Name, tool.Type, tool.Description))		for _, tool := range c.Tools {		sb.WriteString("\nAvailable Tools:\n")	if len(c.Tools) > 0 {			len(c.Tools), len(c.Messages), len(c.State)))	sb.WriteString(fmt.Sprintf("Tools: %d | Messages: %d | State: %d\n",		}		sb.WriteString(fmt.Sprintf("Model: %s\n", c.Metadata.Model))	if c.Metadata.Model != "" {		sb.WriteString(fmt.Sprintf("Agent: %s | Source: %s\n", c.Metadata.Agent, c.Metadata.Source))	sb.WriteString(fmt.Sprintf("TOON Context v%s\n", c.Version))	var sb strings.Builderfunc (c *Context) ToString() string {// ToString returns a human-readable string representation}	return string(data), nil	}		return "", fmt.Errorf("failed to marshal TOON context: %w", err)	if err != nil {	data, err := json.Marshal(b.context)func (b *Builder) ToCompactJSON() (string, error) {// ToCompactJSON converts context to compact JSON (minimal tokens)}	return string(data), nil	}		return "", fmt.Errorf("failed to marshal TOON context: %w", err)	if err != nil {	data, err := json.MarshalIndent(b.context, "", "  ")func (b *Builder) ToJSON() (string, error) {// ToJSON converts context to JSON string}	return b.contextfunc (b *Builder) Build() Context {// Build returns the constructed TOON context}	return b	})		Timestamp: time.Now().UTC().Format(time.RFC3339),		ToolID:    toolID,		Content:   content,		Role:      role,	b.context.Messages = append(b.context.Messages, Message{func (b *Builder) AddToolMessage(role string, content string, toolID string) *Builder {// AddToolMessage adds a tool-related message}	return b	})		Timestamp: time.Now().UTC().Format(time.RFC3339),		Content:   content,		Role:      role,	b.context.Messages = append(b.context.Messages, Message{func (b *Builder) AddMessage(role string, content string) *Builder {// AddMessage adds a conversation message}	return b	b.context.State[key] = valuefunc (b *Builder) AddState(key string, value interface{}) *Builder {// AddState adds a state entry}	return b	b.context.Tools = append(b.context.Tools, tool)func (b *Builder) AddTool(tool ToolContext) *Builder {// AddTool adds a tool to the context}	return b	b.context.Metadata.Environment = envfunc (b *Builder) WithEnvironment(env string) *Builder {// WithEnvironment sets the environment (dev, staging, prod)}	return b	b.context.Metadata.User = userfunc (b *Builder) WithUser(user string) *Builder {// WithUser sets the user identifier}	return b	b.context.Metadata.SessionID = sessionIDfunc (b *Builder) WithSessionID(sessionID string) *Builder {// WithSessionID sets the session identifier}	return b	b.context.Metadata.Model = modelfunc (b *Builder) WithModel(model string) *Builder {// WithModel sets the LLM model}	}		},			Messages: make([]Message, 0),			Tools:    make([]ToolContext, 0),			State:    make(map[string]interface{}),			},				Source:  source,				Agent:   agent,			Metadata: Metadata{			Timestamp: time.Now().UTC().Format(time.RFC3339),			Version:   "1.0",		context: Context{	return &Builder{func NewBuilder(agent string, source string) *Builder {// NewBuilder creates a new TOON context builder}	context Contexttype Builder struct {// Builder helps construct TOON contexts}	Metadata  map[string]interface{} `json:"metadata,omitempty"`	ToolID    string                 `json:"tool_id,omitempty"`	Timestamp string                 `json:"timestamp"`	Content   string                 `json:"content"`	Role      string                 `json:"role"` // user, assistant, system, tooltype Message struct {// Message represents a conversation message with context}	Description string                 `json:"description,omitempty"`	Output      map[string]interface{} `json:"output,omitempty"`	Input       map[string]interface{} `json:"input"`type Example struct {// Example shows sample usage of a tool}	Confidence  float64                `json:"confidence,omitempty"` // 0.0-1.0	Tags        []string               `json:"tags,omitempty"`	Examples    []Example              `json:"examples,omitempty"`	OutputSchema map[string]interface{} `json:"output_schema,omitempty"`	InputSchema map[string]interface{} `json:"input_schema"`	Type        string                 `json:"type"` // openapi, graphql, asyncapi, custom	Description string                 `json:"description"`	Name        string                 `json:"name"`	ID          string                 `json:"id"`type ToolContext struct {// ToolContext represents a tool in TOON format for LLM consumption}	Environment string `json:"environment,omitempty"`	Source      string `json:"source"`	User        string `json:"user,omitempty"`	SessionID   string `json:"session_id,omitempty"`	Model       string `json:"model,omitempty"`	Agent       string `json:"agent"`type Metadata struct {// Metadata contains contextual information about the interaction}	Messages  []Message     `json:"messages,omitempty"`	State     map[string]interface{} `json:"state,omitempty"`	Tools     []ToolContext `json:"tools,omitempty"`	Metadata  Metadata      `json:"metadata"`	Timestamp string        `json:"timestamp"`	Version   string        `json:"version"`type Context struct {// Context represents a TOON (Token-Oriented Object Notation) context for LLM interactions)	"time"	"strings"	"fmt"